name: Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build docs
        run: nix develop .#ci -c mdbook build

      - name: Configure Pages
        if: ${{ github.event.repository.private == false }}
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        if: ${{ github.event.repository.private == false }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: site

  deploy:
    if: ${{ github.event.repository.private == false }}
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v5
